"""add source ingot fields to inspections

Revision ID: 1333fd70e7f8
Revises: b280ac4b811c
Create Date: 2026-05-04 22:17:11.441283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1333fd70e7f8'
down_revision: Union[str, Sequence[str], None] = 'b280ac4b811c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('source_ingot_id', sa.String(length=100), nullable=True))
    op.add_column('inspections', sa.Column('cycle_number', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('sequence_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'sequence_number')
    op.drop_column('inspections', 'cycle_number')
    op.drop_column('inspections', 'source_ingot_id')
    # ### end Alembic commands ###
