"""extend inspections defects images for ai pipeline

Revision ID: 49bb9fd67e7d
Revises: f702508786b9
Create Date: 2026-05-02 15:55:09.140434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bb9fd67e7d'
down_revision: Union[str, Sequence[str], None] = 'f702508786b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defects', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('defects', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('defects', sa.Column('engineer_comment', sa.Text(), nullable=True))
    op.add_column('images', sa.Column('image_type', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('images_inspection_id_fkey'), 'images', type_='foreignkey')
    op.drop_constraint(op.f('images_defect_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'defects', ['defect_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'images', 'inspections', ['inspection_id'], ['id'], ondelete='CASCADE')
    op.add_column('inspections', sa.Column('ingot_id', sa.String(length=100), nullable=True))
    op.add_column('inspections', sa.Column('verdict', sa.String(length=20), nullable=True))
    op.add_column('inspections', sa.Column('max_p_crack', sa.Float(), nullable=True))
    op.add_column('inspections', sa.Column('threshold', sa.Float(), nullable=True))
    op.add_column('inspections', sa.Column('mode', sa.String(length=50), nullable=True))
    op.add_column('inspections', sa.Column('frames_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inspections_ingot_id'), 'inspections', ['ingot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspections_ingot_id'), table_name='inspections')
    op.drop_column('inspections', 'frames_count')
    op.drop_column('inspections', 'mode')
    op.drop_column('inspections', 'threshold')
    op.drop_column('inspections', 'max_p_crack')
    op.drop_column('inspections', 'verdict')
    op.drop_column('inspections', 'ingot_id')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_defect_id_fkey'), 'images', 'defects', ['defect_id'], ['id'])
    op.create_foreign_key(op.f('images_inspection_id_fkey'), 'images', 'inspections', ['inspection_id'], ['id'])
    op.drop_column('images', 'image_type')
    op.drop_column('defects', 'engineer_comment')
    op.drop_column('defects', 'confirmed_at')
    op.drop_column('defects', 'status')
    # ### end Alembic commands ###
