"""add ai model fields to inspections

Revision ID: 9856667a08e9
Revises: c880edc2c273
Create Date: 2026-05-05 15:46:05.871666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9856667a08e9'
down_revision: Union[str, Sequence[str], None] = 'c880edc2c273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('ai_model_id', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('ai_model_key', sa.String(length=100), nullable=True))
    op.add_column('inspections', sa.Column('ai_model_name', sa.String(length=255), nullable=True))
    op.add_column('inspections', sa.Column('ai_model_type', sa.String(length=50), nullable=True))
    op.add_column('inspections', sa.Column('ai_model_architecture', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'inspections', 'ai_models', ['ai_model_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_column('inspections', 'ai_model_architecture')
    op.drop_column('inspections', 'ai_model_type')
    op.drop_column('inspections', 'ai_model_name')
    op.drop_column('inspections', 'ai_model_key')
    op.drop_column('inspections', 'ai_model_id')
    # ### end Alembic commands ###
