"""add shifts table and link inspections

Revision ID: b280ac4b811c
Revises: 49bb9fd67e7d
Create Date: 2026-05-04 18:26:58.879069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b280ac4b811c'
down_revision: Union[str, Sequence[str], None] = '49bb9fd67e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('total_ingots', sa.Integer(), nullable=True),
    sa.Column('processed_ingots', sa.Integer(), nullable=True),
    sa.Column('total_crack', sa.Integer(), nullable=True),
    sa.Column('total_ok', sa.Integer(), nullable=True),
    sa.Column('defect_rate', sa.Float(), nullable=True),
    sa.Column('avg_max_p_crack', sa.Float(), nullable=True),
    sa.Column('avg_frames', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inspections', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inspections_shift_id'), 'inspections', ['shift_id'], unique=False)
    op.create_foreign_key(None, 'inspections', 'shifts', ['shift_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_index(op.f('ix_inspections_shift_id'), table_name='inspections')
    op.drop_column('inspections', 'shift_id')
    op.drop_table('shifts')
    # ### end Alembic commands ###
